
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Mar 13 10:53:12 COT 2021
//----------------------------------------------------

package Principal;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int WHERE = 4;
  public static final int FROM = 3;
  public static final int AND = 5;
  public static final int SELECT = 2;
  public static final int Numero = 17;
  public static final int OR = 6;
  public static final int Mayor = 11;
  public static final int ERROR = 18;
  public static final int Identificador = 16;
  public static final int Coma = 14;
  public static final int EOF = 0;
  public static final int Todo = 7;
  public static final int MenorIgual = 12;
  public static final int error = 1;
  public static final int MayorIgual = 13;
  public static final int Menor = 10;
  public static final int Igual = 8;
  public static final int Diferente = 9;
  public static final int PuntoComa = 15;
}

